import type { Metadata } from "next";
import Navbar from "@/Components/Navbar/Navbar";
import Sidebar from "@/Components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Blog Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-gray-50">
        <Sidebar/>

        <div className="flex flex-col gap-5 w-full flex-1">
          <Navbar/>
        <div className="px-6 py-4">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
