import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/providers/ClientProvider";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Blog Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
        {children}
        </ClientProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
